### ISSUE TITLE
PHP support?

### ISSUE THREAD

**Issue by Potherca** [lsqio/container-factory#1]
It would be nice to have support for PHP. :smiley_cat:

**Comment by edef1c** [comment]
I'm not familiar with PHP's package management — I'll need to know what the equivalents to `npm install` and `npm start` are in PHP-land.

**Comment by Potherca** [comment]
The package manager for PHP is [Composer](https://getcomposer.org).

As far as I know Composer does not have a `start` command. The equivalent for `npm install` is [`composer install`](https://getcomposer.org/doc/03-cli.md#install). By default this will also install development dependencies.

Composer allows user to [declare which platform packages are needed](https://getcomposer.org/doc/02-libraries.md#platform-packages). Optionally these dependencies could be read and installed, although this might fall outside of the responsibility of container-factory.

If you need more info, feel free to ask :smile:
